docker_explorer:
        build: .
        ports:
                - 8084:80
        environment:
                - IP_HEADER=X_TRUE_IP
        volumes:
                - ./persistent/db:/app/db
        restart: unless-stopped

