"""add group to control access to servers

Revision ID: 076558dbe5d3
Revises: 0b829e879cdb
Create Date: 2021-06-13 11:55:45.913200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076558dbe5d3'
down_revision = '0b829e879cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('options', sa.String(length=2000), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docker_server', type_='foreignkey')
    op.drop_column('docker_server', 'group_id')
    op.drop_constraint(None, 'app_user', type_='foreignkey')
    op.drop_column('app_user', 'group_id')
    op.drop_table('server_group')
    # ### end Alembic commands ###
