"""add server secondary table

Revision ID: 076558d4iuoi34433
Revises: 076558d4335d3,
Create Date: 2021-06-13 11:55:45.913200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076558d4iuoi34433'
down_revision = '076558d4335d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_group_server',
    sa.Column('server_group_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_group_server')
    # ### end Alembic commands ###
