"""add profile fields to user

Revision ID: 0b829e879cdb
Revises: 66800f3dbd9e
Create Date: 2021-06-05 22:02:30.594908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b829e879cdb'
down_revision = '66800f3dbd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('app_user', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('app_user', sa.Column('options', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'options')
    op.drop_column('app_user', 'last_name')
    op.drop_column('app_user', 'first_name')
    # ### end Alembic commands ###
