"""add action type

Revision ID: 2c30e5ecf5af
Revises: 8b5c4f2401be
Create Date: 2021-06-26 18:57:00.992677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c30e5ecf5af'
down_revision = '8b5c4f2401be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_record', sa.Column('action_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_record', 'action_type')
    # ### end Alembic commands ###
