"""add user type

Revision ID: 37448553782d
Revises: 8b6760c5d34a
Create Date: 2020-01-27 10:46:53.449465
d
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37448553782d'
down_revision = '8b6760c5d34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.String(length=255), nullable=True))
    op.execute("UPDATE USER SET USER_TYPE = 'admin', active = TRUE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
