"""add container_name to commands to track what container it belongs to

Revision ID: 66800f3dbd9e
Revises: 59264cbeb7c3
Create Date: 2021-05-30 13:59:58.572583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66800f3dbd9e"
down_revision = "59264cbeb7c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("command", sa.Column("container_name", sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("command", "container_name")
    # ### end Alembic commands ###
