"""add access to server group

Revision ID: ddb400e10258
Revises: 076558d4iuoi34433
Create Date: 2021-06-14 06:37:25.084437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb400e10258'
down_revision = '076558d4iuoi34433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_group', sa.Column('access_type', sa.String(length=5), nullable=True))
    op.create_foreign_key(None, 'server_group_server', 'server_group', ['server_group_id'], ['id'])
    op.create_foreign_key(None, 'server_group_server', 'docker_server', ['server_id'], ['id'])
    op.create_foreign_key(None, 'server_group_user', 'app_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'server_group_user', 'server_group', ['server_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'server_group_user', type_='foreignkey')
    op.drop_constraint(None, 'server_group_user', type_='foreignkey')
    op.alter_column('server_group_user', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('server_group_user', 'server_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'server_group_server', type_='foreignkey')
    op.drop_constraint(None, 'server_group_server', type_='foreignkey')
    op.alter_column('server_group_server', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('server_group_server', 'server_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('server_group', 'access')
    op.drop_constraint(None, 'docker_server', type_='foreignkey')
    op.drop_constraint(None, 'app_user', type_='foreignkey')
    # ### end Alembic commands ###
